# getLots.py paths
 # path to chrome webdriver
chrome_driver_path: "ENTER YOUR WEBDRIVER PATH" # eg- "/Users/varunwadhwa/Downloads/chromedriver-mac-arm64/chromedriver"

# train.py paths 
# absolute path to project folder
path: "ENTER THE ABSOLUTE PATH TO YOUR PROJECT FOLDER" # eg- "/Users/varunwadhwa/Desktop/Price-Finder"
train: train/images  # train images (relative to 'path')
val: valid/images  # val images (relative to 'path')

# Classes for train.py
names:
  0: hat


#model.py paths
# path to best.pt
model_path: "/runs/detect/train/weights/best.pt"

#priceFinder.py
# ebay api api key info
client_id: "ENTER YOUR CLIENT ID"
client_secret: "ENTER YOUR CLIENT SECRET"
oauth_token: "ENTER YOUR OAUTH USER TOKEN"



